// GENERATED by scripts/gen_parity_vectors.py - do not edit; rerun the script.
//
// taut's codec-parity rows at taut v0.10.0, the tag `cbor.rs` was vendored from:
// `corpus/parity/{int,malformed,bounds}.vectors.json`, contract
// `taut-codec-parity/i64/v1`. taut's Rust runner (`taut.corpus.parity_rust`)
// renders the rows: the int rows by its `_tables`, each malformed or bounds row by
// its `_row`. Beside each decode row is the expectation taut's gate judges the
// `rust` target by. `tests/parity.rs` compiles this file and replays the rows
// against `cbor.rs`; nothing else compiles it.

/// The runner's `#constants` line: the bounds header's depth numbers, which the
/// runtime's `DEFAULT_MAX_DEPTH` and `MAX_DEPTH_CEILING` must equal.
pub const CONSTANTS: &str = "default_max_depth=32;max_depth_ceiling=128";

/// The (tag, field) payloads taut's gate does not compare for Rust, whose runtime
/// does not carry them.
pub const PAYLOAD_EXEMPT: &[(&str, &str)] = &[("IntOverflow", "value")];

/// A round-trip int row: `IntBox { n, by_id }` of taut's parity fixture encodes to
/// `cbor`.
pub struct IntRow {
    pub name: &'static str,
    pub cbor: &'static str,
    pub n: &'static str,
    pub by_id: &'static [(&'static str, &'static str)],
}

/// An encode-fail int row: `value` is outside the `i64` subset, so encode refuses it.
pub struct EncFail {
    pub name: &'static str,
    pub value: &'static str,
}

/// A malformed or bounds row as taut's Rust runner embeds it: its bytes as
/// `(hex, count)` segments; `len`, the expanded length it states, if any; and what
/// a raw row's call passes, its `limits`. A `from_cbor` or `from_wire` row names its
/// message or enum of the parity fixture in `schema`.
pub struct Row {
    pub name: &'static str,
    pub stage: &'static str,
    pub schema: &'static str,
    pub segments: &'static [(&'static str, usize)],
    pub len: Option<usize>,
    pub max_depth: Option<usize>,
    pub max_encoded_len: Option<usize>,
}

/// What taut's gate judges the `rust` target's observation of a row by.
pub enum Expect {
    /// Decodes and re-encodes to `reencode`, or to the row's own bytes where it has
    /// none (D2).
    Accept { reencode: Option<&'static str> },
    /// Refused with `tag`; each payload field named must match as a string.
    Refuse {
        tag: &'static str,
        payload: &'static [(&'static str, &'static str)],
    },
}

/// A malformed or bounds row and its expectation.
pub struct DecodeRow {
    pub row: Row,
    pub expect: Expect,
}

#[rustfmt::skip]
pub const ROUND_TRIP: &[IntRow] = &[
    IntRow { name: "zero", cbor: "a201000280", n: "0", by_id: &[] },
    IntRow { name: "minus-one", cbor: "a201200280", n: "-1", by_id: &[] },
    IntRow { name: "safe-int-max", cbor: "a2011b001fffffffffffff0280", n: "9007199254740991", by_id: &[] },
    IntRow { name: "safe-int-plus-one", cbor: "a2011b00200000000000000280", n: "9007199254740992", by_id: &[] },
    IntRow { name: "i64-max", cbor: "a2011b7fffffffffffffff0280", n: "9223372036854775807", by_id: &[] },
    IntRow { name: "i64-min", cbor: "a2013b7fffffffffffffff0280", n: "-9223372036854775808", by_id: &[] },
    IntRow { name: "map-key-i64-bounds", cbor: "a201000282a2013b7fffffffffffffff0220a2011b7fffffffffffffff0201", n: "0", by_id: &[("-9223372036854775808", "-1"), ("9223372036854775807", "1")] },
    IntRow { name: "safe-int-plus-two", cbor: "a2011b00200000000000010280", n: "9007199254740993", by_id: &[] },
];

#[rustfmt::skip]
pub const ENCODE_FAIL: &[EncFail] = &[
    EncFail { name: "encode-too-large-positive", value: "9223372036854775808" },
    EncFail { name: "encode-too-large-negative", value: "-9223372036854775809" },
    EncFail { name: "encode-u64-max", value: "18446744073709551615" },
];

#[rustfmt::skip]
pub const DECODE_ROWS: &[DecodeRow] = &[
    DecodeRow { row: Row { name: "truncated-u64-argument", stage: "raw_decode", schema: "", segments: &[("1b0000", 1)], len: None, max_depth: None, max_encoded_len: None }, expect: Expect::Refuse { tag: "Truncated", payload: &[] } },
    DecodeRow { row: Row { name: "trailing-byte", stage: "raw_decode", schema: "", segments: &[("0000", 1)], len: None, max_depth: None, max_encoded_len: None }, expect: Expect::Refuse { tag: "TrailingBytes", payload: &[] } },
    DecodeRow { row: Row { name: "invalid-utf8", stage: "raw_decode", schema: "", segments: &[("61ff", 1)], len: None, max_depth: None, max_encoded_len: None }, expect: Expect::Refuse { tag: "InvalidUtf8", payload: &[] } },
    DecodeRow { row: Row { name: "reserved-additional-info-28", stage: "raw_decode", schema: "", segments: &[("1c", 1)], len: None, max_depth: None, max_encoded_len: None }, expect: Expect::Refuse { tag: "UnsupportedInfo", payload: &[("info", "28")] } },
    DecodeRow { row: Row { name: "unsupported-major-tag", stage: "raw_decode", schema: "", segments: &[("c0", 1)], len: None, max_depth: None, max_encoded_len: None }, expect: Expect::Refuse { tag: "UnsupportedMajor", payload: &[("major", "6")] } },
    DecodeRow { row: Row { name: "non-integer-map-key", stage: "raw_decode", schema: "", segments: &[("a1617800", 1)], len: None, max_depth: None, max_encoded_len: None }, expect: Expect::Refuse { tag: "NonIntegerMapKey", payload: &[] } },
    DecodeRow { row: Row { name: "duplicate-map-key", stage: "raw_decode", schema: "", segments: &[("a201000101", 1)], len: None, max_depth: None, max_encoded_len: None }, expect: Expect::Refuse { tag: "DuplicateMapKey", payload: &[("key", "1")] } },
    DecodeRow { row: Row { name: "positive-int-overflow", stage: "raw_decode", schema: "", segments: &[("1b8000000000000000", 1)], len: None, max_depth: None, max_encoded_len: None }, expect: Expect::Refuse { tag: "IntOverflow", payload: &[("value", "9223372036854775808")] } },
    DecodeRow { row: Row { name: "negative-int-overflow", stage: "raw_decode", schema: "", segments: &[("3b8000000000000000", 1)], len: None, max_depth: None, max_encoded_len: None }, expect: Expect::Refuse { tag: "IntOverflow", payload: &[("value", "-9223372036854775809")] } },
    DecodeRow { row: Row { name: "missing-required-field", stage: "from_cbor", schema: "IntBox", segments: &[("a10100", 1)], len: None, max_depth: None, max_encoded_len: None }, expect: Expect::Refuse { tag: "MissingKey", payload: &[("key", "2")] } },
    DecodeRow { row: Row { name: "wrong-type-field", stage: "from_cbor", schema: "IntBox", segments: &[("a20161780280", 1)], len: None, max_depth: None, max_encoded_len: None }, expect: Expect::Refuse { tag: "WrongType", payload: &[("expected", "int")] } },
    DecodeRow { row: Row { name: "unknown-enum", stage: "from_wire", schema: "Mode", segments: &[("1863", 1)], len: None, max_depth: None, max_encoded_len: None }, expect: Expect::Refuse { tag: "UnknownEnum", payload: &[("enum", "Mode"), ("value", "99")] } },
    DecodeRow { row: Row { name: "non-canonical-int-2byte", stage: "raw_decode", schema: "", segments: &[("190005", 1)], len: None, max_depth: None, max_encoded_len: None }, expect: Expect::Refuse { tag: "NonCanonicalInt", payload: &[("value", "5")] } },
    DecodeRow { row: Row { name: "non-canonical-int-8byte", stage: "raw_decode", schema: "", segments: &[("1b0000000000000005", 1)], len: None, max_depth: None, max_encoded_len: None }, expect: Expect::Refuse { tag: "NonCanonicalInt", payload: &[("value", "5")] } },
    DecodeRow { row: Row { name: "negative-map-key", stage: "raw_decode", schema: "", segments: &[("a12000", 1)], len: None, max_depth: None, max_encoded_len: None }, expect: Expect::Refuse { tag: "NegativeMapKey", payload: &[("key", "-1")] } },
    DecodeRow { row: Row { name: "nested-truncated-string", stage: "raw_decode", schema: "", segments: &[("a100636162", 1)], len: None, max_depth: None, max_encoded_len: None }, expect: Expect::Refuse { tag: "Truncated", payload: &[] } },
    DecodeRow { row: Row { name: "bytes-length-over-2^53", stage: "raw_decode", schema: "", segments: &[("5b0020000000000000", 1)], len: None, max_depth: None, max_encoded_len: None }, expect: Expect::Refuse { tag: "Truncated", payload: &[] } },
    DecodeRow { row: Row { name: "array-count-u64-max", stage: "raw_decode", schema: "", segments: &[("9bffffffffffffffff", 1)], len: None, max_depth: None, max_encoded_len: None }, expect: Expect::Refuse { tag: "Truncated", payload: &[] } },
    DecodeRow { row: Row { name: "items-read-in-order", stage: "raw_decode", schema: "", segments: &[("85c0", 1)], len: None, max_depth: None, max_encoded_len: None }, expect: Expect::Refuse { tag: "UnsupportedMajor", payload: &[("major", "6")] } },
    DecodeRow { row: Row { name: "key-first-duplicate", stage: "raw_decode", schema: "", segments: &[("a2010001", 1)], len: None, max_depth: None, max_encoded_len: None }, expect: Expect::Refuse { tag: "DuplicateMapKey", payload: &[("key", "1")] } },
    DecodeRow { row: Row { name: "key-first-text", stage: "raw_decode", schema: "", segments: &[("a16178", 1)], len: None, max_depth: None, max_encoded_len: None }, expect: Expect::Refuse { tag: "NonIntegerMapKey", payload: &[] } },
    DecodeRow { row: Row { name: "key-first-negative", stage: "raw_decode", schema: "", segments: &[("a120", 1)], len: None, max_depth: None, max_encoded_len: None }, expect: Expect::Refuse { tag: "NegativeMapKey", payload: &[("key", "-1")] } },
    DecodeRow { row: Row { name: "major-6-info-28", stage: "raw_decode", schema: "", segments: &[("dc", 1)], len: None, max_depth: None, max_encoded_len: None }, expect: Expect::Refuse { tag: "UnsupportedMajor", payload: &[("major", "6")] } },
    DecodeRow { row: Row { name: "map-key-2^53", stage: "raw_decode", schema: "", segments: &[("a11b002000000000000000", 1)], len: None, max_depth: None, max_encoded_len: None }, expect: Expect::Accept { reencode: None } },
    DecodeRow { row: Row { name: "wrong-type-text", stage: "from_cbor", schema: "OptBox", segments: &[("a201010280", 1)], len: None, max_depth: None, max_encoded_len: None }, expect: Expect::Refuse { tag: "WrongType", payload: &[("expected", "text")] } },
    DecodeRow { row: Row { name: "wrong-type-array", stage: "from_cbor", schema: "OptBox", segments: &[("a201f60200", 1)], len: None, max_depth: None, max_encoded_len: None }, expect: Expect::Refuse { tag: "WrongType", payload: &[("expected", "array")] } },
    DecodeRow { row: Row { name: "optional-absent", stage: "from_cbor", schema: "OptBox", segments: &[("a10280", 1)], len: None, max_depth: None, max_encoded_len: None }, expect: Expect::Refuse { tag: "MissingKey", payload: &[("key", "1")] } },
    DecodeRow { row: Row { name: "empty-message-not-map", stage: "from_cbor", schema: "Empty", segments: &[("00", 1)], len: None, max_depth: None, max_encoded_len: None }, expect: Expect::Refuse { tag: "WrongType", payload: &[("expected", "map")] } },
    DecodeRow { row: Row { name: "map-field-duplicate", stage: "from_cbor", schema: "IntBox", segments: &[("a201000282a201050201a201050202", 1)], len: None, max_depth: None, max_encoded_len: None }, expect: Expect::Refuse { tag: "DuplicateMapKey", payload: &[("key", "5")] } },
    DecodeRow { row: Row { name: "map-entry-keys-first", stage: "from_cbor", schema: "IntBox", segments: &[("a201000281a1016178", 1)], len: None, max_depth: None, max_encoded_len: None }, expect: Expect::Refuse { tag: "MissingKey", payload: &[("key", "2")] } },
    DecodeRow { row: Row { name: "optional-present-null", stage: "from_cbor", schema: "OptBox", segments: &[("a201f60280", 1)], len: None, max_depth: None, max_encoded_len: None }, expect: Expect::Accept { reencode: None } },
    DecodeRow { row: Row { name: "missing-ok-absent", stage: "from_cbor", schema: "Late", segments: &[("a0", 1)], len: None, max_depth: None, max_encoded_len: None }, expect: Expect::Accept { reencode: Some("a101f6") } },
    DecodeRow { row: Row { name: "missing-ok-wrong-type", stage: "from_cbor", schema: "Late", segments: &[("a10101", 1)], len: None, max_depth: None, max_encoded_len: None }, expect: Expect::Refuse { tag: "WrongType", payload: &[("expected", "text")] } },
    DecodeRow { row: Row { name: "text-leading-bom", stage: "raw_decode", schema: "", segments: &[("64efbbbf61", 1)], len: None, max_depth: None, max_encoded_len: None }, expect: Expect::Accept { reencode: None } },
    DecodeRow { row: Row { name: "simple-undefined", stage: "raw_decode", schema: "", segments: &[("f7", 1)], len: None, max_depth: None, max_encoded_len: None }, expect: Expect::Refuse { tag: "UnsupportedInfo", payload: &[("info", "23")] } },
    DecodeRow { row: Row { name: "simple-zero", stage: "raw_decode", schema: "", segments: &[("e0", 1)], len: None, max_depth: None, max_encoded_len: None }, expect: Expect::Refuse { tag: "UnsupportedInfo", payload: &[("info", "0")] } },
    DecodeRow { row: Row { name: "simple-one-byte-torn", stage: "raw_decode", schema: "", segments: &[("f8", 1)], len: None, max_depth: None, max_encoded_len: None }, expect: Expect::Refuse { tag: "UnsupportedInfo", payload: &[("info", "24")] } },
    DecodeRow { row: Row { name: "shapes-filled", stage: "from_cbor", schema: "Shapes", segments: &[("b3013903e702f93e00036f6e61c3af766520e2988320f09d849e0443007fff05f5060107a10101080709000aa101000b83012119012c0c82a10100a101010d838201028081030e82a20161610201a201616202210f82a201f40201a201f502001082a2010202a10101a2010a02a10100118204051282a20161780200a2016179020913646c617465", 1)], len: None, max_depth: None, max_encoded_len: None }, expect: Expect::Accept { reencode: None } },
    DecodeRow { row: Row { name: "shapes-sparse", stage: "from_cbor", schema: "Shapes", segments: &[("b3010002f900000360044005f4060007a1010008f609f60af60b800c800d800e800f80108011f612f613f6", 1)], len: None, max_depth: None, max_encoded_len: None }, expect: Expect::Accept { reencode: None } },
    DecodeRow { row: Row { name: "shapes-missing-ok-absent", stage: "from_cbor", schema: "Shapes", segments: &[("b2010002f900000360044005f4060007a1010008f609f60af60b800c800d800e800f80108011f612f6", 1)], len: None, max_depth: None, max_encoded_len: None }, expect: Expect::Accept { reencode: Some("b3010002f900000360044005f4060007a1010008f609f60af60b800c800d800e800f80108011f612f613f6") } },
    DecodeRow { row: Row { name: "map-str-key-order", stage: "from_cbor", schema: "Shapes", segments: &[("b3010002f900000360044005f4060007a1010008f609f60af60b800c800d800e83a20161610203a20163efbfbf0201a20164f090808002020f80108011f612f613f6", 1)], len: None, max_depth: None, max_encoded_len: None }, expect: Expect::Accept { reencode: None } },
    DecodeRow { row: Row { name: "map-str-key-duplicate", stage: "from_cbor", schema: "Shapes", segments: &[("b3010002f900000360044005f4060007a1010008f609f60af60b800c800d800e82a20161610201a201616102020f80108011f612f613f6", 1)], len: None, max_depth: None, max_encoded_len: None }, expect: Expect::Refuse { tag: "DuplicateMapKey", payload: &[("key", "a")] } },
    DecodeRow { row: Row { name: "map-bool-key-duplicate", stage: "from_cbor", schema: "Shapes", segments: &[("b3010002f900000360044005f4060007a1010008f609f60af60b800c800d800e800f82a201f50200a201f50201108011f612f613f6", 1)], len: None, max_depth: None, max_encoded_len: None }, expect: Expect::Refuse { tag: "DuplicateMapKey", payload: &[("key", "true")] } },
    DecodeRow { row: Row { name: "list-nested-wrong-type", stage: "from_cbor", schema: "Shapes", segments: &[("b3010002f900000360044005f4060007a1010008f609f60af60b800c800d818161780e800f80108011f612f613f6", 1)], len: None, max_depth: None, max_encoded_len: None }, expect: Expect::Refuse { tag: "WrongType", payload: &[("expected", "int")] } },
    DecodeRow { row: Row { name: "unknown-field-round-trip", stage: "from_cbor", schema: "Empty", segments: &[("a10100", 1)], len: None, max_depth: None, max_encoded_len: None }, expect: Expect::Accept { reencode: Some("a0") } },
    DecodeRow { row: Row { name: "unknown-field-beside-known", stage: "from_cbor", schema: "IntBox", segments: &[("a301070281a201010220036178", 1)], len: None, max_depth: None, max_encoded_len: None }, expect: Expect::Accept { reencode: Some("a201070281a201010220") } },
    DecodeRow { row: Row { name: "names-round-trip", stage: "from_cbor", schema: "Names", segments: &[("b81e010102020361630404050506060707088201020982a20161610201a201616202020a0a0b0b0c0c0d0d0e0e0f0f1010111112121382617861791414151516161717181818181819f5181a181a181b82a201010202a201030204181c181c181d181d181e181e", 1)], len: None, max_depth: None, max_encoded_len: None }, expect: Expect::Accept { reencode: None } },
    DecodeRow { row: Row { name: "depth-32-arrays", stage: "raw_decode", schema: "", segments: &[("81", 31), ("80", 1)], len: Some(32), max_depth: None, max_encoded_len: None }, expect: Expect::Accept { reencode: None } },
    DecodeRow { row: Row { name: "depth-33-arrays", stage: "raw_decode", schema: "", segments: &[("81", 32), ("80", 1)], len: Some(33), max_depth: None, max_encoded_len: None }, expect: Expect::Refuse { tag: "TooDeep", payload: &[("limit", "32")] } },
    DecodeRow { row: Row { name: "depth-32-maps", stage: "raw_decode", schema: "", segments: &[("a100", 31), ("a0", 1)], len: Some(63), max_depth: None, max_encoded_len: None }, expect: Expect::Accept { reencode: None } },
    DecodeRow { row: Row { name: "depth-33-maps", stage: "raw_decode", schema: "", segments: &[("a100", 32), ("a0", 1)], len: Some(65), max_depth: None, max_encoded_len: None }, expect: Expect::Refuse { tag: "TooDeep", payload: &[("limit", "32")] } },
    DecodeRow { row: Row { name: "depth-32-scalar-leaf", stage: "raw_decode", schema: "", segments: &[("81", 32), ("00", 1)], len: Some(33), max_depth: None, max_encoded_len: None }, expect: Expect::Accept { reencode: None } },
    DecodeRow { row: Row { name: "depth-33-items-missing", stage: "raw_decode", schema: "", segments: &[("81", 33)], len: Some(33), max_depth: None, max_encoded_len: None }, expect: Expect::Refuse { tag: "TooDeep", payload: &[("limit", "32")] } },
    DecodeRow { row: Row { name: "depth-33-torn-head", stage: "raw_decode", schema: "", segments: &[("81", 32), ("9b00", 1)], len: Some(34), max_depth: None, max_encoded_len: None }, expect: Expect::Refuse { tag: "Truncated", payload: &[] } },
    DecodeRow { row: Row { name: "depth-33-mixed", stage: "raw_decode", schema: "", segments: &[("81a100", 16), ("80", 1)], len: Some(49), max_depth: None, max_encoded_len: None }, expect: Expect::Refuse { tag: "TooDeep", payload: &[("limit", "32")] } },
    DecodeRow { row: Row { name: "depth-100000-arrays", stage: "raw_decode", schema: "", segments: &[("81", 99999), ("80", 1)], len: Some(100000), max_depth: None, max_encoded_len: None }, expect: Expect::Refuse { tag: "TooDeep", payload: &[("limit", "32")] } },
    DecodeRow { row: Row { name: "depth-100000-maps", stage: "raw_decode", schema: "", segments: &[("a100", 99999), ("a0", 1)], len: Some(199999), max_depth: None, max_encoded_len: None }, expect: Expect::Refuse { tag: "TooDeep", payload: &[("limit", "32")] } },
    DecodeRow { row: Row { name: "depth-33-unknown-field", stage: "from_cbor", schema: "IntBox", segments: &[("a30100028009", 1), ("81", 31), ("80", 1)], len: Some(38), max_depth: None, max_encoded_len: None }, expect: Expect::Refuse { tag: "TooDeep", payload: &[("limit", "32")] } },
    DecodeRow { row: Row { name: "depth-32-unknown-field", stage: "from_cbor", schema: "IntBox", segments: &[("a30100028009", 1), ("81", 30), ("80", 1)], len: Some(37), max_depth: None, max_encoded_len: None }, expect: Expect::Accept { reencode: Some("a201000280") } },
    DecodeRow { row: Row { name: "size-at-limit", stage: "raw_decode", schema: "", segments: &[("83010203", 1)], len: Some(4), max_depth: None, max_encoded_len: Some(4) }, expect: Expect::Accept { reencode: None } },
    DecodeRow { row: Row { name: "size-over-limit", stage: "raw_decode", schema: "", segments: &[("83010203", 1)], len: Some(4), max_depth: None, max_encoded_len: Some(3) }, expect: Expect::Refuse { tag: "TooLarge", payload: &[("len", "4"), ("limit", "3")] } },
    DecodeRow { row: Row { name: "size-before-parse", stage: "raw_decode", schema: "", segments: &[("c0c0c0c0", 1)], len: Some(4), max_depth: None, max_encoded_len: Some(3) }, expect: Expect::Refuse { tag: "TooLarge", payload: &[("len", "4"), ("limit", "3")] } },
    DecodeRow { row: Row { name: "size-empty", stage: "raw_decode", schema: "", segments: &[("", 1)], len: Some(0), max_depth: None, max_encoded_len: Some(0) }, expect: Expect::Refuse { tag: "Truncated", payload: &[] } },
    DecodeRow { row: Row { name: "depth-64-declared", stage: "from_cbor", schema: "Tree64", segments: &[("a10181", 31), ("a10180", 1)], len: Some(96), max_depth: None, max_encoded_len: None }, expect: Expect::Accept { reencode: None } },
    DecodeRow { row: Row { name: "depth-65-declared", stage: "from_cbor", schema: "Tree64", segments: &[("a10181", 32), ("a10180", 1)], len: Some(99), max_depth: None, max_encoded_len: None }, expect: Expect::Refuse { tag: "TooDeep", payload: &[("limit", "64")] } },
    DecodeRow { row: Row { name: "raw-ignores-declared", stage: "raw_decode", schema: "", segments: &[("a10181", 31), ("a10180", 1)], len: Some(96), max_depth: None, max_encoded_len: None }, expect: Expect::Refuse { tag: "TooDeep", payload: &[("limit", "32")] } },
    DecodeRow { row: Row { name: "depth-root-decides", stage: "from_cbor", schema: "Holds64", segments: &[("a101", 1), ("a10181", 15), ("a10180", 1)], len: Some(50), max_depth: None, max_encoded_len: None }, expect: Expect::Refuse { tag: "TooDeep", payload: &[("limit", "32")] } },
    DecodeRow { row: Row { name: "depth-2-declared", stage: "from_cbor", schema: "Flat2", segments: &[("a1018100", 1)], len: Some(4), max_depth: None, max_encoded_len: None }, expect: Expect::Accept { reencode: None } },
    DecodeRow { row: Row { name: "depth-3-declared", stage: "from_cbor", schema: "Flat2", segments: &[("a1018180", 1)], len: Some(4), max_depth: None, max_encoded_len: None }, expect: Expect::Refuse { tag: "TooDeep", payload: &[("limit", "2")] } },
    DecodeRow { row: Row { name: "depth-128-ceiling", stage: "from_cbor", schema: "Tree128", segments: &[("a10181", 63), ("a10180", 1)], len: Some(192), max_depth: None, max_encoded_len: None }, expect: Expect::Accept { reencode: None } },
    DecodeRow { row: Row { name: "depth-129-ceiling", stage: "from_cbor", schema: "Tree128", segments: &[("a10181", 64), ("a10180", 1)], len: Some(195), max_depth: None, max_encoded_len: None }, expect: Expect::Refuse { tag: "TooDeep", payload: &[("limit", "128")] } },
    DecodeRow { row: Row { name: "raw-depth-128", stage: "raw_decode", schema: "", segments: &[("81", 127), ("80", 1)], len: Some(128), max_depth: Some(128), max_encoded_len: None }, expect: Expect::Accept { reencode: None } },
    DecodeRow { row: Row { name: "raw-depth-129", stage: "raw_decode", schema: "", segments: &[("81", 128), ("80", 1)], len: Some(129), max_depth: Some(128), max_encoded_len: None }, expect: Expect::Refuse { tag: "TooDeep", payload: &[("limit", "128")] } },
    DecodeRow { row: Row { name: "raw-depth-capped", stage: "raw_decode", schema: "", segments: &[("81", 128), ("80", 1)], len: Some(129), max_depth: Some(1000), max_encoded_len: None }, expect: Expect::Refuse { tag: "TooDeep", payload: &[("limit", "128")] } },
    DecodeRow { row: Row { name: "len-8-declared", stage: "from_cbor", schema: "Sized8", segments: &[("a101450102030405", 1)], len: Some(8), max_depth: None, max_encoded_len: None }, expect: Expect::Accept { reencode: None } },
    DecodeRow { row: Row { name: "len-9-declared", stage: "from_cbor", schema: "Sized8", segments: &[("a10146010203040506", 1)], len: Some(9), max_depth: None, max_encoded_len: None }, expect: Expect::Refuse { tag: "TooLarge", payload: &[("len", "9"), ("limit", "8")] } },
    DecodeRow { row: Row { name: "len-root-decides", stage: "from_cbor", schema: "HoldsSized8", segments: &[("a101a1014a", 1), ("00010203040506070809", 1)], len: Some(15), max_depth: None, max_encoded_len: None }, expect: Expect::Accept { reencode: None } },
];
