#!/usr/bin/env python3
"""Write (or --check) crates/taut-shape/src/parity_vectors.rs from taut's parity rows.

taut's parity gate (`tautc parity`) replays taut's own sources. This crate ships a
vendored copy of taut's Rust runtime, `crates/taut-shape/src/cbor.rs`, so
`crates/taut-shape/tests/parity.rs` replays the same rows against that copy in
`cargo test` (TautCheckedDecode.md CD-C3). The crate has no JSON parser, so the rows
become a Rust table beside `cbor.rs`.

taut's own Rust runner, `taut.corpus.parity_rust`, renders the rows: the int rows by
its `_tables`, and each malformed or bounds row by its `_row`. This script adds what
the runner leaves to the gate: the expectation the gate judges the `rust` target by
(`parity.row_expect`), the payload fields it exempts for Rust (`parity.PAYLOAD_EXEMPT`)
and the bounds header's constants (`parity.expected_constants`). It refuses rows that
taut's own validation refuses.

The rows must come from the taut tag `cbor.rs` was vendored from. The table names that
tag, which it reads from `cbor.rs`'s `Source :` line. Run it from anywhere, with taut's
checkout beside this repository (the taut-dev layout) at that tag:

    python3 scripts/gen_parity_vectors.py            # rewrite the table
    python3 scripts/gen_parity_vectors.py --check    # exit 1 if the table is stale

`--taut DIR` names another checkout. taut is imported from `DIR/src`, never from an
installed taut-proto, which carries no corpus, and no bytecode is written into it.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path
from types import ModuleType

REPO = Path(__file__).resolve().parents[1]
SRC = REPO / "crates" / "taut-shape" / "src"
TABLE = SRC / "parity_vectors.rs"
RUNTIME = SRC / "cbor.rs"
# `cbor.rs`'s provenance line: `// Source : taut/src/taut/gen/runtime/... at taut v0.10.0.`
SOURCE_TAG = re.compile(r"^// Source : \S+ at taut (v\S+?)\.?$", re.M)
# Literals the table may hold: printable ASCII, whose JSON quoting is also Rust's.
PLAIN = re.compile(r"[ -~]*")

HEADER = """\
// GENERATED by scripts/gen_parity_vectors.py - do not edit; rerun the script.
//
// taut's codec-parity rows at taut {tag}, the tag `cbor.rs` was vendored from:
// `corpus/parity/{{int,malformed,bounds}}.vectors.json`, contract
// `{contract}`. taut's Rust runner (`taut.corpus.parity_rust`)
// renders the rows: the int rows by its `_tables`, each malformed or bounds row by
// its `_row`. Beside each decode row is the expectation taut's gate judges the
// `rust` target by. `tests/parity.rs` compiles this file and replays the rows
// against `cbor.rs`; nothing else compiles it.

/// The runner's `#constants` line: the bounds header's depth numbers, which the
/// runtime's `DEFAULT_MAX_DEPTH` and `MAX_DEPTH_CEILING` must equal.
pub const CONSTANTS: &str = {constants};

/// The (tag, field) payloads taut's gate does not compare for Rust, whose runtime
/// does not carry them.
pub const PAYLOAD_EXEMPT: &[(&str, &str)] = &[{exempt}];

/// A round-trip int row: `IntBox {{ n, by_id }}` of taut's parity fixture encodes to
/// `cbor`.
pub struct IntRow {{
    pub name: &'static str,
    pub cbor: &'static str,
    pub n: &'static str,
    pub by_id: &'static [(&'static str, &'static str)],
}}

/// An encode-fail int row: `value` is outside the `i64` subset, so encode refuses it.
pub struct EncFail {{
    pub name: &'static str,
    pub value: &'static str,
}}

/// A malformed or bounds row as taut's Rust runner embeds it: its bytes as
/// `(hex, count)` segments; `len`, the expanded length it states, if any; and what
/// a raw row's call passes, its `limits`. A `from_cbor` or `from_wire` row names its
/// message or enum of the parity fixture in `schema`.
pub struct Row {{
    pub name: &'static str,
    pub stage: &'static str,
    pub schema: &'static str,
    pub segments: &'static [(&'static str, usize)],
    pub len: Option<usize>,
    pub max_depth: Option<usize>,
    pub max_encoded_len: Option<usize>,
}}

/// What taut's gate judges the `rust` target's observation of a row by.
pub enum Expect {{
    /// Decodes and re-encodes to `reencode`, or to the row's own bytes where it has
    /// none (D2).
    Accept {{ reencode: Option<&'static str> }},
    /// Refused with `tag`; each payload field named must match as a string.
    Refuse {{
        tag: &'static str,
        payload: &'static [(&'static str, &'static str)],
    }},
}}

/// A malformed or bounds row and its expectation.
pub struct DecodeRow {{
    pub row: Row,
    pub expect: Expect,
}}

#[rustfmt::skip]
pub const ROUND_TRIP: &[IntRow] = &[
{round_trip}
];

#[rustfmt::skip]
pub const ENCODE_FAIL: &[EncFail] = &[
{encode_fail}
];

#[rustfmt::skip]
pub const DECODE_ROWS: &[DecodeRow] = &[
{decode_rows}
];
"""


def load_taut(taut: Path) -> tuple[ModuleType, ModuleType]:
    """taut's `parity` and `parity_rust`, imported from `taut/src`."""
    taut = taut.resolve()
    src = taut / "src"
    if not (src / "taut" / "corpus" / "parity_rust.py").is_file():
        raise SystemExit(f"{taut}: not a taut checkout (no src/taut/corpus/parity_rust.py)")
    sys.dont_write_bytecode = True
    sys.path.insert(0, str(src))
    from taut.corpus import parity, parity_rust

    if parity.ROOT.resolve() != taut:
        raise SystemExit(f"taut was imported from {parity.ROOT}, not {taut}")
    return parity, parity_rust


def vendored_tag() -> str:
    """The taut tag `cbor.rs`'s provenance header names."""
    found = SOURCE_TAG.findall(RUNTIME.read_text(encoding="utf-8"))
    if len(found) != 1:
        raise SystemExit(f"{RUNTIME}: expected one '// Source : ... at taut vX.Y.Z' line")
    return found[0]


def literal(parity_rust: ModuleType, value: str) -> str:
    """A Rust string literal, by the runner's own quoting (`_rs`), for printable ASCII."""
    if not PLAIN.fullmatch(value):
        raise SystemExit(f"cannot render {value!r}: the table holds printable ASCII only")
    return parity_rust._rs(value)


def expectation(parity: ModuleType, parity_rust: ModuleType, row: dict) -> str:
    """The `Expect` taut's gate judges the `rust` target's report of `row` by. A payload
    value is compared as `str()` of the JSON value, as the gate compares it."""
    expect = parity.row_expect(parity_rust.TARGET, row)
    if expect.get("accept"):
        reencode = expect.get("reencode")
        rendered = "None" if reencode is None else f"Some({literal(parity_rust, reencode)})"
        return f"Expect::Accept {{ reencode: {rendered} }}"
    payload = ", ".join(
        f"({literal(parity_rust, name)}, {literal(parity_rust, str(expect[name]))})"
        for name in parity.PAYLOAD_FIELDS
        if name in expect
    )
    return f"Expect::Refuse {{ tag: {literal(parity_rust, expect['tag'])}, payload: &[{payload}] }}"


def decode_row(parity: ModuleType, parity_rust: ModuleType, row: dict) -> str:
    """The runner's `Row` for `row`, with its expectation beside it."""
    rendered = parity_rust._row(row).strip()
    if not (rendered.startswith("Row { ") and rendered.endswith(" },")):
        raise SystemExit(f"taut's parity_rust._row changed its form: {rendered[:60]!r}")
    return f"    DecodeRow {{ row: {rendered[:-1]}, expect: {expectation(parity, parity_rust, row)} }},"


def render(parity: ModuleType, parity_rust: ModuleType, tag: str) -> str:
    round_trip, encode_fail, _ = parity_rust._tables()
    exempt = sorted(parity.PAYLOAD_EXEMPT.get(parity_rust.TARGET, ()))
    text = HEADER.format(
        tag=tag,
        contract=parity.CONTRACT,
        constants=literal(parity_rust, parity.expected_constants()),
        exempt=", ".join(f"({literal(parity_rust, t)}, {literal(parity_rust, f)})" for t, f in exempt),
        round_trip=round_trip,
        encode_fail=encode_fail,
        decode_rows="\n".join(decode_row(parity, parity_rust, row) for row in parity.decode_rows()),
    )
    if "\\u" in text:
        raise SystemExit("a rendered literal holds a JSON \\u escape, which Rust does not read")
    return text


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--taut", type=Path, default=REPO.parent / "taut",
                        help="taut checkout at the tag cbor.rs names (default: ../taut)")
    parser.add_argument("--check", action="store_true",
                        help="exit 1 if the committed table differs from a fresh render")
    args = parser.parse_args(argv)
    parity, parity_rust = load_taut(args.taut)
    # Rows taut's own gate would refuse are not vendored.
    counts = (parity.validate_int_vectors(), parity.validate_malformed_vectors(),
              parity.validate_bounds_vectors())
    text = render(parity, parity_rust, vendored_tag())
    table = TABLE.relative_to(REPO)
    if args.check:
        current = TABLE.read_text(encoding="utf-8") if TABLE.is_file() else None
        if current != text:
            print(f"{table} is stale: rerun scripts/gen_parity_vectors.py", file=sys.stderr)
            return 1
        print(f"{table} is current")
        return 0
    TABLE.write_text(text, encoding="utf-8")
    print(f"wrote {table}: {counts[0]} int, {counts[1]} malformed and {counts[2]} bounds rows")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
